main: me.ifamasssxd.horsemodify.HorseModifier
name: HorseModifier
version: '1.6.2'
description: Modifys horse attributes.
commands:
   horsemodify:
      description: Adds the traits.
      aliases: [hm]